export const HANDLECARDCLICK = ' HANDLECARDCLICK';
export const CHECKMATCH = 'CHECKMATCH';
export const CHECKFINISH = 'CHECKFINISH';
export const HANDLERESTART = 'HANDLERESTART';
export const SETCATEGORY = 'SETCATEGORY';
export const FETCHCARDS = 'FETCHCARDS';
export const VSCOMP = 'VSCOMP';